### PR TITLE
Fixed all navbars and redirection from Conversations to About

### PR DESCRIPTION
**Pull request by anujinm**

### CODE REVIEW

**Comment by anujinm** [comment]
these are all small fixes, so I think it would be safe to merge if someone can have a look at it   :)

**Comment by kuanyiwu** [comment]
@anujinm the if else logic for nav bars should be when the user is logged in, they can view their own profile. Right now the profile servlet redirection is in the else statement when user is not logged in

**Comment by anujinm** [comment]
oh gotcha, will fix that. Thanks!

**Comment by sunbini0823** [comment]
cools! Everything looks good.

**Comment by kuanyiwu** [comment]
LGTM!

**Pull request merged**
