### PR TITLE
Added a user picture to MyProfile page.

### PR DESCRIPTION
**Pull request by anujinm**
It looks like this.
image

### CODE REVIEW

**Comment by sunbini0823** [comment]
Except the comment about picture, everything lgtm!!

**Comment by anujinm** [comment]
What comment hha, do you mean I should add comments?

**Comment by anujinm** [comment]
@sunbini0823 yes, the  tests are not complete yet. but I thought it would be good to make pull requests in small portions as we talked before. And we can work on it more and add later. As for the type in register.jsp, I don't know why but when I put type="email", it shows the html default email validation. So in order to show the new email validation, i had to  change it.

**Comment by kuanyiwu** [comment]
@anujinm yeah maybe modify the type to text if you want to do custom email validation, since mail is not a valid type for html input.

**Comment by anujinm** [comment]
@kuanyiwu good idea!  thanks :D

**Pull request merged**
